using cuda
Traceback (most recent call last):
  File "main.py", line 272, in <module>
    output = model(inp_subs)
  File "/beegfs/ga4493/projects/groupb/environments/torch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "main.py", line 180, in forward
    x = self.relu(self.pool(self.cnn2(x)))
  File "/beegfs/ga4493/projects/groupb/environments/torch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/beegfs/ga4493/projects/groupb/environments/torch/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/beegfs/ga4493/projects/groupb/environments/torch/lib/python3.5/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: Given groups=1, weight[8, 16, 3, 3], so expected input[1, 8, 128, 5] to have 16 channels, but got 8 channels instead
